env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "CirrusCI"
    CIRRUS_WORKING_DIR: "/tmp/ci"
    RCLONE: "ENCRYPTED[!d8a3784b8ba0931b52ea6b0ded6c64ec021125f37a44f056fe63c17c47e625b4b45e3b7a66e4ad0336bc6898fd8b848b!]"

task:
  name: Waydroid a11 build
  timeout_in: 260m
  container:
    image: apon77/aosp:cirrus
    cpu: 8
    memory: 32G

  install_script:
    - sudo apt-get update
    - sudo apt-get install -yq neofetch wget
    - neofetch
    - mkdir /home/cirrus/ccache
    - mkdir /home/cirrus/roms

  sync_script:
    - export CCACHE_DIR=~/ccache/
    - export CCACHE_EXEC=$(which ccache)
    - export USE_CCACHE=1
    - ccache -M 8G
    - ccache -z
    - cd /home/cirrus/roms
    - mkdir lineage
    - cd lineage
    - git config --global user.email "xdjust18@gmail.com"
    - git config --global user.name "justxd22"
    - git config --global color.ui true
    - repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-18.1 -g default,-mips,-darwin,-notdefault
    - wget -O - https://raw.githubusercontent.com/Justxd22/waydroid_a11_lineageos/main/manifest.sh | bash
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    - ls -la

  build_script:
    - cd /home/cirrus/roms/lineage
    - source build/envsetup.sh
    - apply-waydroid-patches
    - lunch lineage_waydroid_arm64-userdebug
    - export TZ=Asia/Riyadh
    - make systemimage -j$(nproc --all)
    - make vendorimage -j$(nproc --all)
    - ls -la $OUT_DIR
    - ls -la
    - echo $OUT_DIR

  rclone_script:
    - cd out
    - mkdir -p ~/.config/rclone/
    - echo "$RCLONE" | base64 -d > ~/.config/rclone/rclone.conf
    - rclone copy -v out/system.img drive:waydroid/18.1/"$(date +'%d-%m-%Y:%H:%M')"/
    - rclone copy -v out/vendor.img drive:waydroid/18.1/"$(date +'%d-%m-%Y:%H:%M')"/
